# Top Ranking Group By Request
ranking_count = 20

# Top Slow Requests
slow_count = 37

# Show Standard Deviation column
show_stddev = true

# Show HTTP Status Code columns
show_status_code = true

# Percentiles
percentiles = [ 50.0, 90.0, 95.0, 99.0 ]

# for Nginx($request_time)
scale = 0
effective_digit = 3

# for Apache(%D) and Varnishncsa(%D)
#scale = -6
#effective_digit = 6

# combined + duration
# Nginx example: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'
# Apache example: "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D"
# Varnishncsa example: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %D'
log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" ([0-9.]+)$'

request_index = 5
status_index = 6
duration_index = 10

[bundles]

  # You can aggregate requests by regular expression
  [bundles.memo]
  name = "GET /memo/*"
  regexp = '^GET /memo/[0-9]+ '

  [bundles.stylesheets]
  name = "GET /stylesheets/*"
  regexp = '^GET /stylesheets/'

  [bundles.images]
  name = "GET /images/*"
  regexp = '^GET /images/'
